# Generated by Django 4.2 on 2023-09-05 21:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickUpTime', models.DateTimeField(default=datetime.datetime(2023, 9, 5, 21, 56, 48, 336307, tzinfo=datetime.timezone.utc))),
                ('dropOffTime', models.DateTimeField(default=datetime.datetime(2023, 9, 5, 21, 56, 48, 336307, tzinfo=datetime.timezone.utc))),
                ('pickUpLocation', models.CharField(max_length=100)),
                ('dropOffLocation', models.CharField(max_length=100)),
                ('status', models.CharField(default='CREATED', max_length=20)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
